# docker-compose.yml
version: "3.9"
services:
  db:
    image: pgvector/pgvector:0.7.2-pg16
    container_name: onboarding_pg
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: onboarding
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onboarding -d onboarding"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
