package com.hrpd.onboarding.chain;

import java.util.List;
import java.util.Map;

/**
 * Immutable context that flows across chain steps.
 * Each step can "derive" a new Ctx by adding/changing fields.
 *
 * Fields:
 *  - userText:   original user utterance
 *  - intent:     intent label predicted by IntentStep
 *  - passages:   top-k retrieved passages from VectorStore
 *  - draftAnswer:answer generated by the LLM using retrieved context
 *  - meta:       free-form metadata (e.g., tracing, costs)
 */
public record Ctx(
        String userText,
        String intent,
        List<String> passages,
        String draftAnswer,
        Map<String,Object> meta) {

    /** Returns a copy with an updated intent label. */
    public Ctx withIntent(String i) { return new Ctx(userText, i, passages, draftAnswer, meta); }

    /** Returns a copy with new retrieved passages. */
    public Ctx withPassages(List<String> p) { return new Ctx(userText, intent, p, draftAnswer, meta); }

    /** Returns a copy with a new draft answer. */
    public Ctx withDraft(String d) { return new Ctx(userText, intent, passages, d, meta); }
}
